name: Upload .env

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload .env file
        uses: actions/upload-artifact@v4
        with:
          name: envfile
          path: ResPy/.env
